This is setting up the import package for data pre-processing

In [1]:
import numpy as np
import pandas as pd
from google.colab import drive

Add the datasets to your Google Drive using the links above, then mount your Drive to the notebook by running the cell below.

In [2]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

-----------------------------------------------------------------------------

**SECTION 1: Pre-process for US Household mean income data from the US Census Database**

This is setting up the path for the data file 'data_path' is the variable. Then, run the cell to save your variables. PLEASE UPDATE THE DATA PATH TO REFLECT WHERE YOU STORE THE PRE DATA

In [3]:
data_path = '/content/drive/MyDrive/CIS550_Project/salary.csv' # Path to life expectancy dataset in your drive

Setting up the pandas dataframe. We will take a quick overview of the first 10 rows

In [4]:
df = pd.read_csv(data_path)
df.head(10)

/tmp/ipython-input-4-1101692788.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,80,81,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

,GEO_ID,NAME,S1902_C01_001E,S1902_C01_001M,S1902_C01_002E,S1902_C01_002M,S1902_C01_003E,S1902_C01_003M,S1902_C01_004E,S1902_C01_004M,...,S1902_C03_024M,S1902_C03_025E,S1902_C03_025M,S1902_C03_026E,S1902_C03_026M,S1902_C03_027E,S1902_C03_027M,S1902_C03_028E,S1902_C03_028M,Unnamed: 170
0,Geography,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,NaN
1,860Z200US00601,ZCTA5 00601,5611,258,3158,264,2593,259,897,181,...,**,10043,2868,7271,2050,9659,791,17572,28058,NaN
2,860Z200US00602,ZCTA5 00602,12546,510,6015,504,5241,469,1438,264,...,**,9856,3106,12427,1035,12295,815,18585,6070,NaN
3,860Z200US00603,ZCTA5 00603,19537,671,9162,643,8502,623,1179,215,...,**,14610,2031,17315,3702,13717,720,47278,17781,NaN
4,860Z200US00606,ZCTA5 00606,1871,192,841,150,819,147,33,42,...,**,11335,2014,11533,5516,10321,1134,N,N,NaN
5,860Z200US00610,ZCTA5 00610,8838,459,4977,365,4556,377,1074,228,...,**,13707,2359,13870,1820,14030,1392,12410,9123,NaN
6,860Z200US00611,ZCTA5 00611,611,146,347,138,331,134,52,53,...,**,14357,9210,N,N,13990,3998,N,N,NaN
7,860Z200US00612,ZCTA5 00612,23438,953,11960,729,11093,702,1727,339,...,**,12698,1302,16420,1964,14745,990,12931,8834,NaN
8,860Z200US00616,ZCTA5 00616,3471,369,1639,275,1582,266,264,129,...,**,11488,3213,13523,1993,12248,1308,-,**,NaN
9,860Z200US00617,ZCTA5 00617,8579,524,4797,497,4303,456,820,248,...,**,17536,5654,12897,1145,14256,1584,N,N,NaN

We will drop the first row as it is additional information on the column name. We will also kept the relevant columns

In [5]:
df = df.drop(0)
kept_col = ["GEO_ID", "NAME", "S1902_C03_001E"]
df = df[kept_col]

I save the dataframe to a separate DF to be manipulated.
We will print the row where income is not numeric. The output of the new dataframe shows that we have 1853 row of no income value

In [6]:
modified_data = df
modified_data[~modified_data["S1902_C03_001E"].str.isnumeric()]

               GEO_ID         NAME S1902_C03_001E
89     860Z200US00786  ZCTA5 00786              N
110    860Z200US00934  ZCTA5 00934              N
112    860Z200US00950  ZCTA5 00950              -
119    860Z200US00960  ZCTA5 00960              -
193    860Z200US01097  ZCTA5 01097              N
...               ...          ...            ...
33750  860Z200US99825  ZCTA5 99825              N
33761  860Z200US99850  ZCTA5 99850              -
33763  860Z200US99903  ZCTA5 99903              N
33768  860Z200US99923  ZCTA5 99923              N
33771  860Z200US99927  ZCTA5 99927              N

[1853 rows x 3 columns]

We will first change the name of the column to make it more readable.

In [7]:
modified_data.rename(columns={'GEO_ID': 'GeoID', 'NAME': 'ZipCode', 'S1902_C03_001E': 'MeanIncome'}, inplace=True)

We will parse the 5 unit of digit for the zip code by using regex

In [8]:
modified_data['ZipCode'] = modified_data['ZipCode'].str.extract(r'(\d{5})')

We will take a quick look of the dataframe here

In [9]:
modified_data

                GeoID ZipCode MeanIncome
1      860Z200US00601   00601      24781
2      860Z200US00602   00602      30378
3      860Z200US00603   00603      32478
4      860Z200US00606   00606      25125
5      860Z200US00610   00610      34513
...               ...     ...        ...
33768  860Z200US99923   99923          N
33769  860Z200US99925   99925      96344
33770  860Z200US99926   99926      83973
33771  860Z200US99927   99927          N
33772  860Z200US99929   99929      81514

[33772 rows x 3 columns]

We still have some row where MeanIncome is non-numeric. We will update these values to be Null

In [10]:
modified_data['MeanIncome'] = pd.to_numeric(modified_data['MeanIncome'], errors='coerce')
modified_data

                GeoID ZipCode  MeanIncome
1      860Z200US00601   00601     24781.0
2      860Z200US00602   00602     30378.0
3      860Z200US00603   00603     32478.0
4      860Z200US00606   00606     25125.0
5      860Z200US00610   00610     34513.0
...               ...     ...         ...
33768  860Z200US99923   99923         NaN
33769  860Z200US99925   99925     96344.0
33770  860Z200US99926   99926     83973.0
33771  860Z200US99927   99927         NaN
33772  860Z200US99929   99929     81514.0

[33772 rows x 3 columns]

We will export the completed dataFrame to the path listed here

In [11]:
modified_data.to_csv('/content/drive/MyDrive/CIS550_Project/clean_mean_income.csv', index=False)

-----------------------------------------------------------------------------

**SECTION 2: Pre-process for Housing Data from Realtor.com**

This is the data path for the Realtor dataset. Please update your file path accordingly

In [12]:
data_path = '/content/drive/MyDrive/RDC_Inventory_Core_Metrics_Zip_History.csv'

Setting up the pandas dataframe. We will take a quick overview of the first 10 rows

In [13]:
house = pd.read_csv(data_path)
house.head(10)

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202504,28557,"morehead city, nc",472450.0,-0.0494,-0.1096,65.0,0.2745,0.2150,37.0,...,667288.0,0.0295,0.0863,96.0,0.2244,0.1369,0.4846,-0.0644,-0.1229,1.0
1,202504,48602,"saginaw, mi",84925.0,0.0003,0.3939,59.0,-0.1136,0.2581,52.0,...,129097.0,-0.0285,0.5587,112.0,0.0090,0.2584,0.9231,0.2413,0.0306,0.0
2,202504,53714,"madison, wi",364925.0,-0.0134,0.1450,7.0,0.0000,0.4000,43.0,...,367774.0,-0.0430,0.1328,25.0,0.1667,0.4000,2.4286,0.7143,0.0286,1.0
3,202504,12838,"hartford, ny",118625.0,NaN,-0.7476,1.0,NaN,0.0000,33.0,...,118625.0,NaN,-0.7476,1.0,0.0000,-0.6667,1.0000,NaN,-1.0000,1.0
4,202504,85654,NaN,250000.0,NaN,NaN,1.0,NaN,NaN,2.0,...,250000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0
5,202504,5086,"west topsham, vt",316250.0,-0.0560,-0.3042,2.0,0.0000,0.0000,122.0,...,316250.0,-0.0560,-0.3042,3.0,0.5000,0.2000,0.5000,NaN,0.0000,1.0
6,202504,36915,"needham, al",279900.0,NaN,NaN,0.0,NaN,NaN,72.0,...,279900.0,NaN,NaN,1.0,-0.5000,NaN,NaN,NaN,NaN,0.0
7,202504,78564,NaN,39500.0,NaN,NaN,1.0,NaN,NaN,13.0,...,39500.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0
8,202504,26519,"albright, wv",151000.0,0.0000,-0.7451,2.0,-0.2500,-0.2500,55.0,...,170988.0,0.1324,-0.7114,5.0,0.2500,1.5000,2.3333,1.3333,1.8333,1.0
9,202504,3441,"ashuelot, nh",178000.0,NaN,NaN,0.0,NaN,NaN,67.0,...,178000.0,NaN,NaN,1.0,0.0000,NaN,NaN,NaN,NaN,0.0

We will kept only the relevant column

In [14]:
kept_col = ["month_date_yyyymm", "postal_code", "median_listing_price", "active_listing_count"]
house = house[kept_col]

We will first change the name of the column to make it more readable.

In [15]:
house.rename(columns={'month_date_yyyymm': 'MonthDate', 'postal_code': 'ZipCode', 'median_listing_price': 'MedianListingPrice', 'active_listing_count': 'ActiveListingCount'}, inplace=True)

We will check the type of each column in the Dataframe

In [28]:
house.dtypes

MonthDate              object
ZipCode                object
MedianListingPrice    float64
ActiveListingCount    float64
dtype: object

We will convert the MonthDate to be str type as well

In [27]:
house['MonthDate'] = house['MonthDate'].astype(str)

We will convert the zipcode column to be str type

In [19]:
house['ZipCode'] = house['ZipCode'].astype(str)

We will use zfill to pad the zipCode to be 5 digit.

In [22]:
house['ZipCode'] = house['ZipCode'].str.zfill(5)

In [24]:
house.head(20)

    MonthDate ZipCode  MedianListingPrice  ActiveListingCount
0      202504   28557            472450.0                65.0
1      202504   48602             84925.0                59.0
2      202504   53714            364925.0                 7.0
3      202504   12838            118625.0                 1.0
4      202504   85654            250000.0                 1.0
5      202504   05086            316250.0                 2.0
6      202504   36915            279900.0                 0.0
7      202504   78564             39500.0                 1.0
8      202504   26519            151000.0                 2.0
9      202504   03441            178000.0                 0.0
10     202504   77338            272225.0               120.0
11     202504   63333             99900.0                 1.0
12     202504   98272            954750.0                27.0
13     202504   04576            850000.0                 2.0
14     202504   95333            787000.0                 4.0
15     202504   78060            128500.0                 1.0
16     202504   58622            255000.0                 7.0
17     202504   61856            361150.0                 6.0
18     202504   94525            651250.0                 8.0
19     202504   80453            595000.0                 1.0

Key attribute contain no null. We will export the current dataframe

In [29]:
house.isnull().any()

MonthDate             False
ZipCode               False
MedianListingPrice     True
ActiveListingCount     True
dtype: bool

We will export the dataframe to csv

In [30]:
house.to_csv('/content/drive/MyDrive/CIS550_Project/clean_realtor.csv', index=False)